### ISSUE TITLE
HUBOT_SLACK_CHANNELS doesn't work

### ISSUE THREAD

**Issue by gamafranco** [slackapi/hubot-slack#116]
Hi, I can't find a way to tell hubot to join other channels than #general.

heroku config:set HUBOT_SLACK_CHANNELS=#general,#rails

does nothing.

Thanks.

**Comment by olivierlacan** [comment]
One weird thing that's not intuitive at all is that Hubot will stay in the Slack channel (and even show up with a green dot) when he's been kicked from it (because you can't kick people from #general). He will respond to direct commands mentioning his name but not fire `hear` responses.

This is problematic because we have several teams grouped under one Slack account and one team's automatic responses to certain keyword may greatly annoy another's, so we don't want all Hubots in #general.
