### ISSUE TITLE
Hubot repeats himself upon restart

### ISSUE THREAD

**Issue by dpritchett** [slackapi/hubot-slack#153]
Hi there!  When I ask Hubot a question and he answers it, that's good.  When he restarts 30 minutes later and answers the old question with an old response, that's bad.

Is this a known issue?  I assume Slack is replaying old content to Hubot upon connection and the bot isn't hashing its handled code into the redis-brain so that it can skip replies.  I could look at working up a patch if I get some positive response here.

Thanks :)

**Comment by evansolomon** [comment]
I've never seen this sort of thing.  Can you share some code that replicates it?  Does it happen for every single message (or at least for the ones that trigger Hubot responses)?

**Comment by dpritchett** [comment]
I've just set up a brand new hubot-slack following the instructions here.  The codebase is at github.com/railsdog/railsdogdog .  Every time I restart Heroku the bot repeats messgaes he's already handled.

## Initial trigger and response
![image](https://cloud.githubusercontent.com/assets/147981/6153613/75005872-b1eb-11e4-8563-721eafe082be.png)

## Unwanted, untriggered second response an hour later
![image](https://cloud.githubusercontent.com/assets/147981/6153623/8a996cfa-b1eb-11e4-8bf9-ebf1a40e4d5a.png)

**Comment by dpritchett** [comment]
PS - given that Heroku dyons restart at the drop of a hat this is going to get ugly pretty quickly ;)

**Comment by dpritchett** [comment]
I'm also using Heroku's new deploy-via-github feature.  Once my Travis CI build passes then Heroku builds and launches a new dyno.  Still though, something is either caching and replaying old messages for the bot on connect.  It might be the redis brain but my money's on Slack itself.

**Comment by SamWilliams** [comment]
I'm experiencing the same issue with one of our integrations... though as far as I can tell it appears to have just started happening today. Perhaps something to do with the uptime issues slack is having today? https://status.slack.com/

**Comment by dpritchett** [comment]
Could be a temporary slack hiccup.  Ideally Hubot would be robust enough to
resist this but if the problem goes away I guess there's no need to
overengineer a solution.

**Comment by evansolomon** [comment]
I still can't replicate it but that seems like a good guess.

**Comment by paulhammond** [comment]
This is related to the [issues we're having this morning](https://status.slack.com/). One of the side effects of the problems we're having is that if you reconnect you'll get resent messages you've seen before. This is done for the case of a typical slack client, where receiving the same message twice is not a problem (you can de-dupe based on TS, and display them easily). But it's a problem for bots that perform actions based on those messages.

The problem is going to go away as soon as today's problems are resolved (which is all our ops and core application teams are working on right now). But we should probably be doing a better job of handling this case in the adapter.

One solution would be to use redis to store the last timestamp seen in a channel. We could then ignore any messages before that timestamp (timestamps are guaranteed unique and monotonically increasing). Another alternative would be to use [channels.mark](channels.mark) to store this info on Slack's servers.

I'm open to other ideas?

**Comment by evansolomon** [comment]
> One solution would be to use redis to store the last timestamp seen in a channel. We could then ignore any messages before that timestamp (timestamps are guaranteed unique and monotonically increasing). 

This seems like a good/simple answer.  Only amendment would be to use `robot.brain` rather than redis directly.

**Comment by jpoehls** [comment]
Just a heads up that I'm seeing this issue with my bot this morning.

**Comment by technicalpickles** [comment]
Slightly different, but if people are seeing multiple messages from a single command after a reconnect, https://github.com/slackhq/hubot-slack/issues/210 has some more details.

**Comment by DEGoodmanWilson** [comment]
Some kind of message de-duplication mechanism is probably warranted for these circumstances.

**Comment by johnagan** [comment]
I've not heard that this is still a problem. If so, please reopen.
