### ISSUE TITLE
Add scripting section to README

### ISSUE THREAD

**Issue by technicalpickles** [slackapi/hubot-slack#245]
Similar to https://github.com/github/hubot/blob/master/docs/scripting.md it'd be good to include some examples of Slack-specific behavior. The things that come to mind so far:
- using attachments, ie `robot.emit 'slack-attachment'`
- call the Slack API, ie https://github.com/slackhq/hubot-slack/issues/209

**Comment by nemo** [comment]
+1

**Comment by justmiles** [comment]
+1

**Comment by SammyIsra** [comment]
+1

**Comment by technicalpickles** [comment]
Another thing to document, using custom listeners:

```
 robot.listeners.push new SlackBotListener(robot, regex, callback)
```

This was introduced in https://github.com/slackhq/hubot-slack/pull/133

**Comment by mshwery** [comment]
+1

**Comment by DavidAwad** [comment]
+1

**Comment by piersb** [comment]
+1

**Comment by aaronblythe** [comment]
What I am finding (at least with the PagerDuty Slack integration that I am working with) is that what is shown in Slack is not what is being picked up by `SlackBotListener` so I think this may explain some people's troubles.  I was wasting a lot of time because I thought I could simply replace working `robot.hear` or `robot.respond` functions using the same regex's.

For Slack Integrations/Slack Apps you are working with you may want to start with this:

```
HubotSlack = require 'hubot-slack'

module.exports = (robot) ->
  regex = /(.+)/
  robot.listeners.push new HubotSlack.SlackBotListener robot, regex, (msg) ->
    msg.send "whole message: #{msg.match[1]}"
```

Then compare what you see from the Slack integration vs. what you get out of the `SlackBotListener`.

For example, from the PagerDuty Slack integration I get (formatted prettier with links but this is really just a copy/paste):

```
pagerduty BOT [2:32 PM] 
Resolved: Incident #267 (XXXXX)
----------------
botdefault

Resolved By
----------------
Aaron Blythe

description
----------------
test bot cycle - @ablythe

View Incident Details
```

From the msg.send in the snippet above I get:

```
MyBot BOT [2:32 PM]
whole message: Resolved: Incident (botdefault (https://team.pagerduty.com/services/XXXXX)): description: test bot cycle - @ablythe (read more (https://team.pagerduty.com/incidents/XXXXX))
```

I don't know enough about the code that produces this message in Slack to know if this is intentional or a bug.  At the very least is violates the principle of least astonishment (since things like #267 are just missing).  I am finding that simple snip above to be tremendously helpful in helping me understand why things are not working.  Hope this helps someone else.

**Comment by JonathanRosado** [comment]
+1

**Comment by rowi1de** [comment]
I'm missing an info how to get the channel name? Currently I only get a room id via the following snippet:

`# helper method to get channel of originating message
  get_channel = (response) ->
    if response.message.room == response.message.user.name
      "@#{response.message.room}"
    else
      "##{response.message.room}"`

Maybe related to this change: https://github.com/slackhq/hubot-slack/issues/328

**Comment by technicalpickles** [comment]
See https://github.com/slackhq/hubot-slack/pull/314 for the current usage of attachments.

**Comment by johnagan** [comment]
I don't believe this specific addition is still valid anymore, but the API docs are due for additional examples. Reopen as needed.
