### ISSUE TITLE
Listening for image upload (file_created)

### ISSUE THREAD

**Issue by genxstylez** [slackapi/hubot-slack#397]
As titled. Is this supported?

**Comment by aoberoi** [comment]
there is no support for the `"file_created"` RTM API event in this adapter.

can you describe your use case? i'd be open to hearing a proposal for an API. it would probably look something like `Robot::react()` that is implemented currently, because it goes beyond the standard Hubot interface and set of `Message` classes.

**Comment by daniel-beard** [comment]
+1 I have a similar use case, to listen to and run code snippets that are posted.

**Comment by aoberoi** [comment]
thanks for the PR, it looks really good! i left some feedback there for you. happy to help get that across the finish line 😄

**Comment by shanedewael** [comment]
Addressed with #546
