### ISSUE TITLE
get private channel info

### ISSUE THREAD

**Issue by andreash92** [slackapi/hubot-slack#437]
Hello, 
how to use `getChannelGroupOrDMByName( )`  ?

I tried this `robot.adapter.client.rtm.dataStore.getChannelByName('channelName')` with no luck. i am getting an error that this is not a function. 

I am succesfully using this `robot.adapter.client.rtm.dataStore.getChannelByName()` and `getGroupNyName()` which they are for public and private channels respectively but my problem is that sometimes hubot knows just the channel name and not if that channel is private or not, so calling for example the `getChannelByName()` for a private channel, results in an error.  

thanks

**Comment by samkshah** [comment]
Were you able to get this resolved? I'm having same issue - trying to get additional information about channel when it's created, e.g. if the channel is public or private, channel purpose, etc. I'm trying to avoid `https://api.slack.com/methods/channels.info` API call if I can. I believe HUBOT's builtin slack client can handle such requests. Just not sure how.

**Comment by aoberoi** [comment]
Hey friends, sorry this took a while to get to. My recommendation is to not depend on the `dataStore` at all, it will be removed in the future (see #385). Instead, this problem can be solved by using the relatively new Conversations API method [`conversations.info`](https://api.slack.com/methods/conversations.info), which can normalize the differences between public channels, private channels (groups), DMs, and MPDMs. note that this method requires an ID, **not a name**.

i know @samkshah wanted to avoid making an API call, but that would be the most reliable way to get the information. since the introduction of Shared Channels user names and channel names are not guaranteed to be unique. and since the introduction of Enterprise Grid, the `dataStore` is not guaranteed to contain complete information about the workspace (team).
