### ISSUE TITLE
Get a list of all mentioned users in a message

### ISSUE THREAD

**Issue by healthycola** [slackapi/hubot-slack#450]
### Description

Hello! New to hubot, and I was wondering if it's possible to get all the users mentioned in a message. Something like "hubot Raise a bug on @Wendy about <Title>". Hubot gives me the mentioned user (in this case, Wendy), and I can raise a bug on her in our backend.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
hey @healthycola, this is an interesting idea. its not implemented right now, but i could see this being added as a new method on `SlackTextMessage`. it should be a pretty to implement using a RegExp to match the [user mention syntax](https://api.slack.com/docs/message-formatting#linking_to_channels_and_users).

just a note: you really want to only rely on **user IDs** when programmatically using the APIs, not user names. the Slack platform has moved away from any uniqueness garantees with usernames since Shared Channels launched. See the [changelog entry](https://api.slack.com/changelog/2017-09-the-one-about-usernames).

**Comment by aoberoi** [comment]
this issue will be fixed by #465

**Comment by shanedewael** [comment]
Fixed by #465 
`mentions` array now passed with messages, which holds `SlackMention` objects that contain the type of mention (`user` or `conversation`), the `id` for the corresponding user or conversation, and if available, an `info` object returned by Slack with more user info (https://api.slack.com/methods/users.info) or conversation info (https://api.slack.com/methods/conversations.info)
