### ISSUE TITLE
document looking up user IDs in a slack message and warn against using username or display_name

### ISSUE THREAD

**Issue by csoni111** [slackapi/hubot-slack#462]
### Description

Slack api has changed how usernames are stored. Previously the display name _(the one we use in the slack interface to tag other people by prepending @ symbol)_, were given for `name` key in user's data fetched from slack api. But now slack has changed that, the `name` field no more gives the user's display name on slack, instead it gives a slack generated string which user cannot change. The display name is now given in `profile.display_name`.

This needs to be updated [here](https://github.com/slackapi/hubot-slack/blob/7add9cae09a571523b0201c78ca0b1a36c6b26c2/src/bot.coffee#L239). This will enable the hubot's [robot.brain.userForName](https://github.com/hubotio/hubot/blob/8b0b8a9ba80e6d65df2e644b106c43d4b309d01f/src/brain.js#L151:L163) to return the correct result.

Slack api change log link: [A lingering farewell to the username](https://api.slack.com/changelog/2017-09-the-one-about-usernames#changing)

**Relevant part : User objects**
User objects encountered throughout the platform will continue having a name (AKA `@username` and sometimes even `user_name` or `username`) field but:

- Users will be less likely to manually set their `@username` as it will rarely surface in any part of the Slack product.
- Users created after September 11, 2017 will have their `@username` set for them.
- User objects' profile will contain the `display_name` and `display_name_normalized` fields, indicating the user's preferred name.
- `display_name` is not unique and may contain a relatively full gamut of UTF-8 characters. Emoji and a limited range of characters are not allowed.
- Existing users created before September 11, 2017 will have their `display_name` set to their current name value.
- Users will begin setting their display names now.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] testing related
- [ ] documentation related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

hubot-slack version: 4.4.0

**Comment by aoberoi** [comment]
@csoni111 you're right that the `name` field being deprecated at the platform level has some big implications for Hubot and this adapter.

the implications are actually that `username` should be *no longer be depended upon * for programmatic use. however `profile.display_name` also is not recommended for programmatic use, so simply substituting one for the other will not fix problems. for example, the `display_name` can be updated by the user or other apps. this will cause lookups in the brain with `robot.brain.userForName` to fail also. rather than switching from one unreliable source of data to another, i think users of this adapter need a better understanding of what they can and cannot expect from the Brain, whose design is not compatible with this change.

the best way forward would be to document that `robot.brain.userForName()` does not lookup users by display name when using this adapter. its not something most hubot script authors should work with, its only useful in a very small set of cases. *you need to write your scripts to only use user IDs.* after #450 is addressed (in the next release) you'll find the user IDs for all users mentioned in a message as a property on the message, so its easy to look up.

in the very small set of cases where a display name is needed, the way to find it is the following:

```javascript
const displayName = 'someDisplayNameYouWantToFind';
const user = robot.brain.data.users.find((user) => user.profile.display_name == displayName);
```
