### ISSUE TITLE
Reaction handler does not include text of message that was reacted to

### ISSUE THREAD

**Issue by david4shure** [slackapi/hubot-slack#469]
### Description

When I setup a reaction handler like such

```robot.react(handleReaction);```

and in my handleReaction function I have the following code

```
  let handleReaction = function(res) {
    let message = res.message;
    let reaction = message.reaction;
    let roomname = getRoomName(robot, res);

    console.log(res.message.text);
  }
```

When I react to a message to test this, `res.message.text` is undefined. I can't get the text of the message that was reacted to from the reaction handler. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.4.0

node version:6.11.1

OS version(s):Ubuntu

#### Steps to reproduce:

1. Setup code above for reaction handler
2. React to a message, see that `res.message.text` is undefined.

#### Expected result:

`res.message.text` should have the text of the message that was reacted to.

#### Actual result:

`res.message.text` is undefined.

**Comment by aoberoi** [comment]
`res.message` is an instance of `ReactionMessage`, which isn't meant to have a `text` property. instead, it will have a `item` property. the contents of that property depend on exactly what the reaction was on, and is described [on this documentation page](https://api.slack.com/events/reaction_added#embedded_item_objects).

in order to get the text of a message, i would do something like this:

```
let handleReaction = function(res) {
    const item = res.message.item;
    if (item.type === 'message') {
      robot.adapter.web.channels.history(item.channel, {
        count: 1,
        inclusive: true,
        latest: item.ts
      })
        .then((result) => {
          const message = result.messages[0];
          if (message.ts !== item.ts) { throw new Error(); }
          console.log(message.text); // TADA!
        })
        .catch(() => res.send('could not find message in channel'));
  }
```

there if you run into an error, it's possible that you are using an App Bot instead of a Custom Bot, which does not have the `channels:history` scope required for this technique to work. if that's the case, and you're only creating an internal integration for a single workspace, I'd advise you to switch to a Custom Bot.

**Comment by david4shure** [comment]
I am getting that stacktrace. 

```ERROR TypeError: Cannot read property 'channels' of undefined```

So the way I have hubot configured is via Slack Apps. 

<img width="250" alt="screen shot 2018-03-30 at 10 33 39 am" src="https://user-images.githubusercontent.com/1820642/38147332-a6b03d9c-3406-11e8-9b50-58688e5c53f4.png">

You are saying that I should configure it with Custom Apps like such?

<img width="243" alt="screen shot 2018-03-30 at 10 40 17 am" src="https://user-images.githubusercontent.com/1820642/38147365-d8796d4e-3406-11e8-9ac0-1c73b1c7918c.png">

**Comment by aoberoi** [comment]
@david4shure two things:

1) I think you want to set up Hubot using the custom integrations instead of the app option. the easiest way is to follow this link: https://my.slack.com/services/new/bot. once you fill out the username you will see an app token (it starts with `xoxb`) on the configuration page. that is the token you should use when starting Hubot (use it as the value for `HUBOT_SLACK_TOKEN` environment variable).

2) the error in the stacktrace seems unrelated to the permissions in the token, so there's something else wrong too. i think i made a typo, can you replace `robot.adapter.web` with `robot.adapter.client.web`? (i've updated my previous comment)
