### ISSUE TITLE
hubot-slack won't stay connected on Enterprise Grid slack instance

### ISSUE THREAD

**Issue by davewongillies** [slackapi/hubot-slack#477]
### Description

hubot-slack doesn't appear to stay connected on an Enterprise Grid slack instance. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

We've just upgraded our slack instance to an Enterprise Grid instance. Up until that point, while running on a free plan, hubot had been fine. Now after the upgrade, I see continually see this:

```
2018-04-19T19:15:53.988705+00:00 app[web.1]: [Thu Apr 19 2018 19:15:53 GMT+0000 (UTC)] INFO Logged in as hubot of my_slack
2018-04-19T19:15:54.186944+00:00 app[web.1]: [Thu Apr 19 2018 19:15:54 GMT+0000 (UTC)] INFO Slack client now connected
2018-04-19T19:16:05.374894+00:00 app[web.1]: [Thu Apr 19 2018 19:16:05 GMT+0000 (UTC)] ERROR undefined
2018-04-19T19:16:05.375269+00:00 app[web.1]: warn: Reconnecting, on attempt 1
```

Sometimes it will stay connected for minutes, other times, it will disconnect almost immediately with the same error.

#### Reproducible in:

* hubot-slack version: 4.4.0
* node version: 8.9.x
* OS version(s): Linux-based OS running on Heroku

#### Steps to reproduce:

1. Connect to an Enterprise Grid slack account
2. Attempt to direct chat (eg `help` command)

Sometimes I get a response back, but mostly hubot will disconnect

#### Expected result:

For hubot to stay connected without the `ERROR undefined` message

#### Actual result:

For hubot continually disconnects with the `ERROR undefined` message

#### Attachments:

![](https://media.giphy.com/media/UOpdmwKA7la0g/giphy.gif)

**Comment by aoberoi** [comment]
@davewongillies in the words of C-3PO

> Sir, it's very possible this asteroid is not stable.

sorry about the troubles. its tough to start debugging this one without knowing where that `ERROR: undefined` is being logged from. let's try to narrow it down. can you share the contents of your `external-scripts.json`? if you start up hubot with an empty `scripts` directory, does this still happen?

also, we're currently preparing a pretty massive update for this package. it might resolve your issue. it might make your issue worse. either way, i'd advise that as soon as that's available (monday or tuesday), you go ahead and update so that we can more effectively work on this issue.

**Comment by davewongillies** [comment]
The issue ended up being the version of `hubot-redis-brain` I had deploy (0.0.4). Bumped it to `^1.0.0` and all is good now.
