### ISSUE TITLE
hubot-slack is using an insecure version of lodash

### ISSUE THREAD

**Issue by aedahl** [slackapi/hubot-slack#490]
### Description

hubot-slack lists a vulnerable version of lodash as a dependency by default.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

https://nodesecurity.io/advisories/577

#### Reproducible in:

hubot-slack version: 4.4.0

node version: 0.10.x

OS version(s): 4.15.15-1-Arch

#### Steps to reproduce:

1. run npm audit

#### Expected result:

No vulnerable versions of lodash used as dependencies of hubot-slack.

#### Actual result: 

Vulnerable version of lodash being used as a dependency of hubot-slack.

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by chriskol** [comment]
I see this was closed by OP but is this not still an issue?  I get vulnerability issues for what appears to be this exact thing.

**Comment by aedahl** [comment]
Hey @chriskol - I believe I was able to just manually change the version that was required, and then update lodash to one that was not vulnerable.

I closed the issue after not getting any response or traction on the issue. I am new to the whole npm/node development world and don’t know the proper method for alerting package maintainers/developers of vulnerabilities, much less getting them to change the default version of a dependency required by their module.

**Comment by chriskol** [comment]
I'm new as well to node.  I'm running this on a heroku server and didn't know how to make the change.  Would you mind explaining how?  The only methods I can think of are to fork hubot-slack and make a new npm repo to call from in hubot's package.json.  Or I suppose drop an edited file in the scripts folder?  But which one?  Thanks in advance if you're able to help!

**Comment by aoberoi** [comment]
Hey folks 👋 maintained here. 

@chriskol Please correct me if I’m wrong, but I don’t think a fresh install of the latest version of `hubot-slack` installs a vulnerable version of lodash. If this is happening for you, it’s likely that your `package-lock.json` is specifying that version. To fix this with minimal changes you should be able to just run `npm audit fix`. 

@aedahl: sorry if you didn’t get the response you were hoping for. I think reporting the issue was the right thing. It doesn’t seem like the issue was open for very long before you closed it yourself, so we probably didn’t feel the need to comment - you had probably figured it out. 

Just FYI, this report includes node v 0.10, which is old *and very insecure*. We dropped support for that node version in this package, and I highly recommend updating to the latest version you can (v10 ideally).

**Comment by chriskol** [comment]
@aoberoi You're correct and thanks for the fast response!  Funny story npm audit fix isn't fixing it "  1 vulnerability requires manual review. See the full report for details." but I think this issue I was getting was related to multiple scripts that happened to be using older lodash versions and I thought it was hubot-slack but it appears I was wrong. Thanks to @aedahl as well!

**Comment by aedahl** [comment]
@aoberoi Thanks for the response! No worries - as you noted, the problem pretty much resolved itself. Funny what reading the docs can do. Oh boy, 0.10? 
@chriskol You’re welcome! Four months can seem like an eternity in the dev world.
