### ISSUE TITLE
User profile undefined in 4.5.1

### ISSUE THREAD

**Issue by jasonfma** [slackapi/hubot-slack#499]
### Description

New error upgrading from 4.5.0 to 4.5.1.
`context.response.message.user.profile.email`
`TypeError: Cannot read property 'email' of undefined`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

hubot-slack version: 4.5.1

node version: 8.11.3

OS version(s):

#### Steps to reproduce:

1. 
```
robot.listenerMiddleware((context, next, done) => {
  return context.response.message.user.profile.email
});
```

#### Expected result:
Get the email of the user

#### Actual result:
`TypeError: Cannot read property 'email' of undefined`

**Comment by shanedewael** [comment]
Hey @jasonfma, sorry about that. This is actually expected, though should have been handled a little more gracefully on our end. We did a little work to standardize the `User` objects because they weren't guaranteed shape or information.

That being said, the same information should be accessible via  `context.response.message.user.email_address` or inside the `profile` of `context.response.message.user.slack` given the user has an email address associated with their account. Let me know if you're still facing issues.

**Comment by jasonfma** [comment]
Thanks @shadiakiki1986 I'll try it out and reopen if this doesn't work.

**Comment by fadookie** [comment]
@shanedewael thanks for the quick response on this one. in the future if you make breaking changes like this could you bump your major version number to respect semver? thanks.
