### ISSUE TITLE
Add URL as variable from slack

### ISSUE THREAD

**Issue by Akhilesh-Anb** [slackapi/hubot-slack#518]
Hi Team,

We have written a script to get the cluster health of elasticsearch provided with URL of cluster in msg.http.

**Question** :  Is there a way to declare URL as variable. I need users to provide URL as a variable in slack and it should be used as cluster URL.

```
robot.hear /health|status/i, (msg) ->
    if msg.message.user.id is robot.name
      return

    clusterHealth msg, msg.match[1], (text) ->
      msg.send text

  clusterHealth = (msg) ->
      msg.http("http://1.2.3.4:9200/_cluster/health")
        .get() (err, res, body) ->
          json = JSON.parse body
          msg.send("The cluster status is `#{json.status}`")
```

Appreciate your help

Thanks,
Akhilesh Appana

**Comment by aoberoi** [comment]
I have a couple suggestions and questions for you.

1. I suggest you name the value in the `robot.hear` callback `res` instead of `msg`. The value represents the various responses you could perform. It's also confusing to deal with `msg.message` (a message inside the message?).

2. I'm not sure how the `clusterHealth` function works as written. It seems like you defined the function to take one argument, `msg`. Yet when you call the function, you are passing it 3 arguments `msg, msg.match[1], callback`. I don't think the function is even using the last 2, so that callback will never run. I suggest you either just remove them, or inline the function code into the `robot.hear` callback.

3. You can use the RegExp to capture and parse more data from the message. I'll give you an example:

```coffeescript
robot.hear /(health|status) (\S*)/i, (res) ->
  url = res.match[2] # TODO: verify the value can be parsed as a URL
  res.http(url + "/_cluster/health")
    .get() (err, _res, body) ->
      json = JSON.parse body
      res.send("The cluster status is #{json.status}")
```

The preceding example should work in the same way when your hubot sees the message `health http://1.2.3.4:9200`, but you can use any URL.
