### ISSUE TITLE
web.api >.usergroups.users.update()

### ISSUE THREAD

**Issue by Plork** [slackapi/hubot-slack#527]
### Description

I am trying to make a bot that add the engineer on duty to a group. I almost have everything working but it's failing on the final step.

Keep in mind I just learned about js/nodejs 3-4 days ago and I am not a developer. So be gentle.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

The problem is that the usergroups.users.update() returns 

```
error: Response not OK:  invalid_array_arg
Unhandled rejection Error: invalid_array_arg
```

#### Reproducible in:

hubot-slack version: 4.5.4

node version: 10.0.0

OS version(s): macosx sierra

#### Steps to reproduce:

I use the following code when this issue happens.

```
web = new WebClient(process.env.SLACK_OAUTH_TOKEN)

web.usergroups.list()
.then(usergroups_result => {
    for (let k in usergroups_result.usergroups) {
    const userGroupName = usergroups_result.usergroups[k].name
    if (userGroupName != null && userGroupName.toLowerCase() === slackUserGroup) {
        var userGroup = usergroups_result.usergroups[k]
    }
    }

    web.usergroups.users.update({
    usergroup: userGroup.team_id,
    users: user.id,
    })
})
.catch(err => res.reply('can\'t deal with this one: ' + err))
```

So I am first going through the usergroups to find it by name. Since not everyone knows their groupId by heart. This results in only 1 group (I checked).

I have a different function that grabs the user and I checked the contents of `user.id` and its only 1 id of the slack user as a string.

I tried to add the users like so: `[user.id].join(",")` but this didn't matter.

#### Expected result:

Response.ok

#### Actual result:

```
error: Response not OK:  invalid_array_arg
Unhandled rejection Error: invalid_array_arg
```

Anyone knows that I am doing wrong? thnx!

**Comment by aoberoi** [comment]
@Plork first of all, you're already off to a great start, esp considering you've only got a few weeks experience! congrats on making the leap 🎉 

i think i see two things that are incorrect. the first is pretty simple. when you call `usergroups.users.update`, the `usergroup` argument should be set to `userGroup.id` (not `team_id`). the second thing is based on something you said: "I am trying to make a bot that add the engineer on duty to a group." if you really want to add a user, then you need to include all the existing users in the `users` argument, otherwise you'd overwrite the list and remove the existing users. in other words, the docs describe the `users` argument with:

> A comma separated string of encoded user IDs that represent the entire list of users for the User Group.

so we need the whole list of users in that user group _appended with_ the user you wish to add. we can get the list by calling [`usergroups.users.list`](https://api.slack.com/methods/usergroups.users.list). you can append the user ID and flatten it out to a comma-separated list like so: `userList.append(user.id).join(',')`.

let us know if you have any more questions and good luck!

**Comment by Plork** [comment]
well actually I want to overwrite the existing users so that's correct. But the team_id > id I will fix.

**Comment by Plork** [comment]
oh lol sorry @EoD forgot get add quotes around it was meant to mimic a slack group, never thought it could have been someone's username ;)

but I am still getting the error:
```
error: Response not OK:  invalid_array_arg
```

after changing team_id to id

**Comment by Plork** [comment]
btw  @aoberoi  thnx for the help i got it working!
