### ISSUE TITLE
robot.brain.usersForFuzzyName(name) issues?

### ISSUE THREAD

**Issue by estiens** [slackapi/hubot-slack#56]
Scripts that use robot.brain.usersForFuzzyName(name) to match users and store data about them

(like the ubiquitous https://github.com/github/hubot/blob/master/src/scripts/roles.coffee)

do not seem to work correctly using Slack. Seems to be an issue with how Slack is storing the user object, because anytime someone clears their session cookies by closing their browser the roles script loses all memory of them)

**Comment by mshwery** [comment]
I actually still have this issue running the latest hubot-slack (`v3.3.0`)

Part of the problem seems to be timing-related, as we are using `redis-brain` for hubot, which connects _after_ the adapter runs and loads the brain with users. The users are getting overwritten when the redis-brain (even when all keys in redis are cleared) connects. Perhaps I should take issue with redis-brain instead, but if the adapter were to load last, that seems to be ideal.
