### ISSUE TITLE
Can not trigger listener sometimes.

### ISSUE THREAD

**Issue by yihchu** [slackapi/hubot-slack#641]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: ^4.10.0

node version: v14.15.3

OS version(s): cenos7.9

#### Steps to reproduce:

1. new a hubot
2. add it into a slack channel
3. modify 'example.coffee'
4. start hubot

#### Expected result:

After send 'hello', it replies 'Hello World.'
After send 'badger', it replies 'Badgers? BADGERS? WE DON'T NEED NO STINKIN BADGERS'

#### Actual result:

Sometimes, it goes well, but sometimes, the same text can not trigger the listener.
Please see the logs.

#### Attachments:
I send 'hello' and 'badger', sometimes it goes well, like this:
```
[Fri Jul 15 2022 10:21:30 GMT+0800 (中国标准时间)] DEBUG Message 'jokerr hello' matched regex //hello/i/; listener.options = { id: null }
[Fri Jul 15 2022 10:21:30 GMT+0800 (中国标准时间)] DEBUG Executing listener callback for Message 'jokerr hello'
[Fri Jul 15 2022 10:21:30 GMT+0800 (中国标准时间)] DEBUG SlackClient#send() room: D03PG99UQ7M, message: Hello World.
[Fri Jul 15 2022 10:21:38 GMT+0800 (中国标准时间)] DEBUG Received text message in channel: D03PG99UQ7M, from: W9Z9MFWHG (human)
[Fri Jul 15 2022 10:21:38 GMT+0800 (中国标准时间)] DEBUG Message 'jokerr badger' matched regex //badger/i/; listener.options = { id: null }
[Fri Jul 15 2022 10:21:38 GMT+0800 (中国标准时间)] DEBUG Executing listener callback for Message 'jokerr badger'
[Fri Jul 15 2022 10:21:38 GMT+0800 (中国标准时间)] DEBUG SlackClient#send() room: D03PG99UQ7M, message: Badgers? BADGERS? WE DON'T NEED NO STINKIN BADGERS
```
But sometimes....
```
[Fri Jul 15 2022 10:17:34 GMT+0800 (中国标准时间)] DEBUG Received text message in channel: D03PG99UQ7M, from: W9Z9MFWHG (human)
[Fri Jul 15 2022 10:17:43 GMT+0800 (中国标准时间)] DEBUG Received file_shared message from: undefined, file_id: F03PP89C0BE
[Fri Jul 15 2022 10:17:43 GMT+0800 (中国标准时间)] DEBUG No listeners executed; falling back to catch-all
```

And here is the screenshot of slack
<img width="580" alt="截屏2022-07-15 10 30 58" src="https://user-images.githubusercontent.com/11792362/179135127-c98e2a96-49be-4d90-a864-5e07ca6c1b41.png">

**Comment by seratch** [comment]
Hi @yihchu, thanks for asking the question.

> DEBUG Received file_shared message from: undefined, file_id: F03PP89C0BE

This log line indicates the message has an attached file. Thus, this one cannot be part of your screenshot. Please check the channel history again. Also, even when a message has attached files, as long as your message text contains "badger", your listener can react to the message for sure.

**Comment by yihchu** [comment]
> 

Please ignore the log about file, please check the logs around it. i did send a text 'hello', and it did received(`DEBUG Received text message in channel: D03PG99UQ7M, from: W9Z9MFWHG (human)`), but it didn't trigger any listener(`DEBUG No listeners executed; falling back to catch-all`)

**Comment by yihchu** [comment]
> Hi @yihchu, thanks for asking the question.
> 
> > DEBUG Received file_shared message from: undefined, file_id: F03PP89C0BE
> 
> This log line indicates the message has an attached file. Thus, this one cannot be part of your screenshot. Please check the channel history again. Also, even when a message has attached files, as long as your message text contains "badger", your listener can react to the message for sure.

Hi @seratch ,please check this. 
https://github.com/slackapi/hubot-slack/issues/642#issuecomment-1185183614

I reproduced, and I take a new screenshot and logs.

**Comment by seratch** [comment]
Hi @yihchu, I've checked your comment in #642 and tried to see the same situation on my end. However, my Hubot app does not miss any messages. Also, we do not see any outage / incident reports on the RTM API (= underlying WebSocket connectivity) at this moment.

The only possible cause that I can think of is that your Hubot app's WebSocket connection might be a bit unstable due to something specific to your network environment (or anything between Slack server and your Hubot app process). In this case, the Slack server-side could fail to occasionally send message events to your app. 

To narrow the issue down, I would suggest trying to run the same app in a completely different setting (say, on a different cloud service) and see how it goes. If your situation persists regardless of where to run your Hubot app, something wrong may be happening to your workspace or Hubot app configuration. To resolve this, please contact our customer support team from either `/feedback` in your Slack workspace or https://my.slack.com/help/requests/new .

Lastly, if you don't have any particular reason to use Hubot, we highly recommend using a newer platform feature for new app development. Most of the things that Hubot w/ Slack adapter can be done with [Bolt framework](https://api.slack.com/tools/bolt) along with [Socket Mode](https://api.slack.com/apis/connections/socket) + [Events API](https://api.slack.com/events?filter=Events) in a better way. Refer to the [Getting Started Guide](https://slack.dev/bolt-js/tutorial/getting-started) for learning how to use it.

I hope this was helpful to you and everything will work well for you soon.

**Comment by yihchu** [comment]
> 
@seratch 
Thanks. And could you tell me the ports that hubot uses.

**Comment by yihchu** [comment]
> Hi @yihchu, I've checked your comment in #642 and tried to see the same situation on my end. However, my Hubot app does not miss any messages. Also, we do not see any outage / incident reports on the RTM API (= underlying WebSocket connectivity) at this moment.
> 
> The only possible cause that I can think of is that your Hubot app's WebSocket connection might be a bit unstable due to something specific to your network environment (or anything between Slack server and your Hubot app process). In this case, the Slack server-side could fail to occasionally send message events to your app.
> 
> To narrow the issue down, I would suggest trying to run the same app in a completely different setting (say, on a different cloud service) and see how it goes. If your situation persists regardless of where to run your Hubot app, something wrong may be happening to your workspace or Hubot app configuration. To resolve this, please contact our customer support team from either `/feedback` in your Slack workspace or https://my.slack.com/help/requests/new .
> 
> Lastly, if you don't have any particular reason to use Hubot, we highly recommend using a newer platform feature for new app development. Most of the things that Hubot w/ Slack adapter can be done with [Bolt framework](https://api.slack.com/tools/bolt) along with [Socket Mode](https://api.slack.com/apis/connections/socket) + [Events API](https://api.slack.com/events?filter=Events) in a better way. Refer to the [Getting Started Guide](https://slack.dev/bolt-js/tutorial/getting-started) for learning how to use it.
> 
> I hope this was helpful to you and everything will work well for you soon.

@seratch Thanks. Could you tell me the ports that hubot uses.
