### ISSUE TITLE
RTMClient failed to connect

### ISSUE THREAD

**Issue by tom10271** [slackapi/hubot-slack#651]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/hubot-slack/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

hubot-slack version: 4.10.0

node version: v18

OS version(s): mac 12

#### Steps to reproduce:

1. Install Hubot and this adapter via npm
2. Run 
```
HUBOT_SLACK_RTM_CLIENT_OPTS='{ "retryConfig": { "retries": 20 },"logLevel": "debug" }' HUBOT_SLACK_TOKEN=xoxb-xxxxxx HUBOT_LOG_LEVEL=debug NODE_ENV=production PORT=8084 hubot -a slack -l my-crashed-slack-bot
```

#### Expected result:
Works

#### Actual result:
```
[Tue Mar 14 2023 14:14:27 GMT+0000 (UTC)] DEBUG Loading adapter slack
[Tue Mar 14 2023 14:14:27 GMT+0000 (UTC)] INFO hubot-slack adapter v4.10.0
debug: BaseAPIClient _createFacets end
debug: BaseAPIClient initialized
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
debug: BaseAPIClient registerDataStore end
debug: RTMClient initialized
[Tue Mar 14 2023 14:14:27 GMT+0000 (UTC)] DEBUG RtmClient initialized with options: {"retryConfig":{"retries":20},"logLevel":"debug","useRtmConnect":true,"maxRequestConcurrency":1}
[Tue Mar 14 2023 14:14:27 GMT+0000 (UTC)] DEBUG RtmClient#start() with options: {}
verbose: Attempting to connect via the RTM API
debug: BaseAPIClient _makeAPICall end
verbose: BaseAPIClient _callTransport - Retrying [object Object]
debug: BaseAPIClient _callTransport end
verbose: BaseAPIClient _callTransport - Retrying [object Object]
verbose: BaseAPIClient _callTransport - Retrying [object Object]
verbose: BaseAPIClient _callTransport - Retrying [object Object]
verbose: BaseAPIClient _callTransport - Retrying [object Object]
verbose: BaseAPIClient _callTransport - Retrying [object Object]
```

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by pabloalr** [comment]
+1

**Comment by bandra** [comment]
+1

**Comment by kingjason** [comment]
+1

**Comment by Ventsi** [comment]
+1

**Comment by kebshell** [comment]
Some Slack services had certificate renewals deployed this morning. Updating CA certs fixed this issue for me

**Comment by kylegibson-rldatix** [comment]
@kebshell Any instructions you can share on updating CA certs on heroku?

**Comment by bandra** [comment]
is this fixed for anyone? Still broken here

**Comment by ton31337** [comment]
+1

**Comment by scheerer** [comment]
@kebshell are you able to share how you accomplished updating the CA certs? The only workaround we've found is to disable TLS/SSL

**Comment by kylegibson-rldatix** [comment]
Following up with @scheerer's comment, I was able to work around the issue by setting `NODE_TLS_REJECT_UNAUTHORIZED=0`. Definitely not a long term solution.

**Comment by mwbrooks** [comment]
Hey all, sorry to hear that you're experiencing connection issues! 😓 

@kebshell is correct that today there was an SSL cert change and it's impact some developers.

Here is a link to the incident's status: [Some users may experience issues accessing api.slack.com](https://status.slack.com/2023-03/9011b8a984a74042).

It's good to hear that a short-term workaround is to disable TLS/SSL, but I agree that it's not a long-term solution.

If you're still affected, I'd recommend to first reach out to Slack Support because it's good to have an official record of those impacted. They'll also be one of the first to know when the issue is resolved and to recommend a solution for others:
* feedback@slack.com
* or...
* https://slack.com/help/requests/new
    * Enter the topic as "Slack API: RTM Connection Failing" (or something along those lines)

I believe, if you're able to update your CA certs, then you should be able to get Slack's updated SSL certificates. However, if you're using Heroku or another platform-as-a-service then this may not be in your control. I'll keep an eye on this as well and try to share any knowledge that I see!

**Comment by denzhel** [comment]
> Following up with @scheerer's comment, I was able to work around the issue by setting `NODE_TLS_REJECT_UNAUTHORIZED=0`. Definitely not a long term solution.

You are a life saver ! Production is back up !

**Comment by darthsteven** [comment]
If you're in a PaaS type situation (we're on platform.sh) then I can recommend going to very latest node runtime supported, and then it starts working again :)
